/// Flutter icons CatSomething
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CatSomething
///      fonts:
///       - asset: fonts/CatSomething.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CatSomethingIcons {
  CatSomethingIcons._();

  static const _kFontFam = 'CatSomething';
  static const String? _kFontPkg = null;

  static const IconData mouse =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmute =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
